// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVQ5psy9F99NCmHsedb6m0udV-L_6vDOE',
    appId: '1:713848751978:web:df47c875e6d7da1180c713',
    messagingSenderId: '713848751978',
    projectId: 'mealflavor-9cf79',
    authDomain: 'mealflavor-9cf79.firebaseapp.com',
    storageBucket: 'mealflavor-9cf79.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyActIiZd8mVQ3b_sDsK9tr3wQUXwbnvr98',
    appId: '1:713848751978:android:1045007572729fc080c713',
    messagingSenderId: '713848751978',
    projectId: 'mealflavor-9cf79',
    storageBucket: 'mealflavor-9cf79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATcg9KklAKQdP_4Uw8Ajz4TOudDJbZA2s',
    appId: '1:713848751978:ios:13a34b82ddad934e80c713',
    messagingSenderId: '713848751978',
    projectId: 'mealflavor-9cf79',
    storageBucket: 'mealflavor-9cf79.firebasestorage.app',
    iosBundleId: 'com.example.antiGaspillageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATcg9KklAKQdP_4Uw8Ajz4TOudDJbZA2s',
    appId: '1:713848751978:ios:13a34b82ddad934e80c713',
    messagingSenderId: '713848751978',
    projectId: 'mealflavor-9cf79',
    storageBucket: 'mealflavor-9cf79.firebasestorage.app',
    iosBundleId: 'com.example.antiGaspillageApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVQ5psy9F99NCmHsedb6m0udV-L_6vDOE',
    appId: '1:713848751978:web:924d5e82bc6b05b780c713',
    messagingSenderId: '713848751978',
    projectId: 'mealflavor-9cf79',
    authDomain: 'mealflavor-9cf79.firebaseapp.com',
    storageBucket: 'mealflavor-9cf79.firebasestorage.app',
  );
}
